apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 840658508063.dkr.ecr.us-east-2.amazonaws.com/mc-kube:gatewaysvc-v3
          ports:
            - containerPort: 80